labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for checking out FilaOps! We'd love to hear about your experience.
  - type: textarea
    id: setup-experience
    attributes:
      label: Setup Experience
      description: How did your installation go? What worked, what didn't?
      placeholder: |
        - Did you get it running?
        - What OS are you on?
        - Any errors or confusion?
    validations:
      required: false
  - type: textarea
    id: use-case
    attributes:
      label: Your Use Case
      description: What are you hoping to use FilaOps for?
      placeholder: |
        - How many printers?
        - What's your current workflow?
        - What features matter most to you?
    validations:
      required: false
  - type: textarea
    id: feature-requests
    attributes:
      label: Feature Requests
      description: What would make FilaOps perfect for your farm?
    validations:
      required: false
